version: "3.8"

services:
  mysqldb:
    image: mysql:8.3
    restart: unless-stopped
    env_file: ./.env
    environment:
      - MYSQL_PASSWORD=$DB_PASSWORD
      - MYSQL_ROOT_PASSWORD=$MYSQL_ROOT_PASSWORD
      - MYSQL_DATABASE=$MYSQLDB_DATABASE
    ports:
      - "${MYSQLDB_LOCAL_PORT}:${MYSQLDB_DOCKER_PORT}"
    volumes:
      - db:/var/lib/mysql
    networks:
      - my_network
    healthcheck:
          test: ["CMD", "mysqladmin", "ping", "-h", "mysqldb"]
          interval: 10s
          retries: 5
          timeout: 5s
      
  backend:
    build: 
      context: ./backend       
      dockerfile: Dockerfile
    env_file: .env
    depends_on:
      mysqldb:
        condition: service_healthy
    environment:
      - JWT_SECRET=${JWT_SECRET}
      - SPRING_APPLICATION_JSON={"spring.datasource.url":"jdbc:mysql://mysqldb:$MYSQLDB_DOCKER_PORT/$MYSQLDB_DATABASE?allowPublicKeyRetrieval=true&defaultAuthenticationPlugin=caching_sha2_password","spring.datasource.username":"$DB_USERNAME","spring.datasource.password":"$DB_PASSWORD","spring.jpa.hibernate.ddl-auto":"update"}
    networks:
      - my_network
    ports:
      - "8080:8080"         

  frontend:
    build:
      context: ./frontend  
      target: prod
    environment:
      - NODE_ENV=prod

    container_name: task-frontend
    networks:
      - my_network
    ports:
      - "80:80"          
    depends_on:
      - backend


volumes:
  db:

networks:
  my_network:
    driver: bridge
