CREATE TABLE IF NOT EXISTS user (
  id BIGINT AUTO_INCREMENT PRIMARY KEY,

  email VARCHAR(254) NOT NULL UNIQUE,
  password VARCHAR(64) NOT NULL,

  user_name VARCHAR(32) NOT NULL,
  user_role VARCHAR(64) NOT NULL DEFAULT 'user'
);


CREATE TABLE IF NOT EXISTS task (
  id INT AUTO_INCREMENT PRIMARY KEY,
  user_id BIGINT NOT NULL,

  title VARCHAR(50) NOT NULL,
  description VARCHAR(500) NOT NULL,

  status VARCHAR(20) NOT NULL DEFAULT 'PENDING',
  priority VARCHAR(20) NOT NULL DEFAULT 'LOW',

  due_date TIMESTAMP NULL,
  created_date TIMESTAMP NOT NULL,

  CONSTRAINT fk_task_user
    FOREIGN KEY (user_id)
    REFERENCES `user` (id)
    ON DELETE CASCADE
);


